metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        version: ${project.version}    
    spec:                 
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Dspring.profiles.active=prod
        - name: JAVA_ENABLE_DEBUG
          value: "false"
        imagePullPolicy: Always   
      imagePullSecrets:
      - name: secret-aliyuncs
           
                    