metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8084
  selector:
    project: ${project.artifactId}
    
