metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  ports:
  - name: web
    port: 8083
    targetPort: 8083
  selector:
    project: ${project.artifactId}
    
